fieldLayouts:
  7d214f5a-e593-42d8-880d-2ad1d77afcdb:
    tabs:
      -
        elements:
          -
            instructions: null
            label: Title
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: 1d7e1462-56b8-49f3-a8ce-0275093cbe52
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 6ec04abd-e956-4b82-97ed-70134ead2c4e
            required: true
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: aeb93271-5acf-40c1-a884-b93d5c104432
            required: true
            type: craft\fieldlayoutelements\CustomField
        name: 'Tab 1'
        sortOrder: 1
handle: blog
hasTitleField: true
name: Blog
section: 4b46fb02-0c00-410b-b74a-0e0d23c895e8
sortOrder: 1
titleFormat: ''
