fieldLayouts:
  e702dafa-7843-48bf-afac-35fe674f5a54:
    tabs:
      -
        elements:
          -
            instructions: null
            label: ''
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: 29794e70-7e50-43f7-8468-e2c9e07c6e3b
            required: true
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 97adc0df-a586-44dd-9f59-9af552e3df9b
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: aeb93271-5acf-40c1-a884-b93d5c104432
            required: true
            type: craft\fieldlayoutelements\CustomField
        name: Content
        sortOrder: 1
      -
        elements:
          -
            fieldUid: eeb15d1e-8e1a-4c22-96c2-a94d937d706d
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: SEO
        sortOrder: 2
handle: home
hasTitleField: false
name: Home
section: fed63747-c99e-42ea-9279-3887a6577fa1
sortOrder: 1
titleFormat: '{section.name|raw}'
