fieldLayouts:
  a8a48015-7a46-4dea-ae8d-c12206c38674:
    tabs:
      -
        elements:
          -
            instructions: null
            label: ''
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: 29794e70-7e50-43f7-8468-e2c9e07c6e3b
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: Content
        sortOrder: 1
      -
        elements:
          -
            fieldUid: eeb15d1e-8e1a-4c22-96c2-a94d937d706d
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: SEO
        sortOrder: 2
handle: work
hasTitleField: false
name: Work
section: 3f070327-46b8-48c0-9cfd-6740e6d696cc
sortOrder: 1
titleFormat: '{section.name|raw}'
