fieldLayouts:
  72c4a8f7-9c17-499e-822c-4493659475be:
    tabs:
      -
        elements:
          -
            instructions: null
            label: Title
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: 29794e70-7e50-43f7-8468-e2c9e07c6e3b
            required: true
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 97adc0df-a586-44dd-9f59-9af552e3df9b
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: d099a350-1403-4e1a-8210-93ff4503edcc
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 98462fb3-3a47-43a5-9ced-e8c24683cf00
            required: true
            type: craft\fieldlayoutelements\CustomField
        name: 'Tab 1'
        sortOrder: 1
handle: work
hasTitleField: true
name: Work
section: 15eef8ab-d95e-4f24-80fc-23f9c5801e6b
sortOrder: 1
titleFormat: ''
