contentColumnType: text
fieldGroup: c7a6a1c5-3848-4ca0-9f8e-c8670f54b2cc
handle: postContent
instructions: ''
name: 'Post Content'
searchable: true
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  cleanupHtml: true
  columnType: text
  purifierConfig: ''
  purifyHtml: ''
  redactorConfig: Standard.json
  removeEmptyTags: ''
  removeInlineStyles: ''
  removeNbsp: ''
  showUnpermittedFiles: false
  showUnpermittedVolumes: true
translationKeyFormat: null
translationMethod: none
type: craft\redactor\Field
