contentColumnType: string(255)
fieldGroup: c7a6a1c5-3848-4ca0-9f8e-c8670f54b2cc
handle: projectLink
instructions: ''
name: 'Project Link'
searchable: true
settings:
  maxLength: '255'
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Url
