contentColumnType: text
fieldGroup: c7a6a1c5-3848-4ca0-9f8e-c8670f54b2cc
handle: subTitle
instructions: ''
name: 'Sub Title'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
