enableVersioning: true
handle: work
name: Work
propagationMethod: all
siteSettings:
  8e2e27db-740d-4d18-97b9-c59553de574e:
    enabledByDefault: true
    hasUrls: true
    template: work/index
    uriFormat: work
type: single
